title: Jackie Wang's Homepage.
email: falwat@163.com
description: >- # this means to ignore newlines until "baseurl:"
  学海无涯, 厚积薄发; 道阻且长, 行则将至!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://falwat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  falwat

# Build settings
theme: jekyll-theme-midnight
